# Generated by Django 3.0.2 on 2020-01-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200126_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hide_email',
            field=models.BooleanField(default=True),
        ),
    ]
