# Generated by Django 3.0.2 on 2020-01-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_log', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readinglog',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='readinglog',
            old_name='user_id',
            new_name='user',
        ),
    ]
