# Generated by Django 3.0.2 on 2020-02-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200204_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
